### ISSUE TITLE
Documentation of CLI options

### ISSUE THREAD

**Issue by ffdead** [jenius/autoprefixer-stylus#86]
Hi,

Are there any examples of how to pass the `browsers` option when using the CLI interface?

Thanks!

**Comment by jenius** [comment]
I might ask this question in the stylus repo rather than here, as it's a question about to to use Stylus' CLI interface rather than about this plugin or anything that happens with it specifically. Personally I never use the CLI so I can't give a good answer here.

I might ask something like "Is there a way to pass arguments to stylus plugins through the CLI interface?"

Good luck and sorry I can't be more helpful!

**Comment by icflorescu** [comment]
It's been a while since this was raised, but meanwhile the `--with` argument has been added to the [stylus docs page](http://stylus-lang.com/docs/executable.html).

I'm sure other people will bump into this nevertheless, so I'll just mention it for reference here:
`stylus < test.styl --use ../node_modules/autoprefixer-stylus --with "{ browsers: ['ie 7', 'ie 8'] }"`
